legaltalks_src/account/urls.py
from django.urls import path
from . import views as account_views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('signup/advocate/', account_views.advocate_signup, name='advocate-signup'),
    path('signup/advocate/verification/', account_views.code_verification, name='code-verification'),
    path('signup/advocate/join/', account_views.verification_success, name='verification-success'),
    path('signup/advocate/resend-code/', account_views.resend_code, name='resend-code'),
    path('signup/', account_views.user_signup, name='user-signup'),
    path('signup/profile-creation/', account_views.profile_signup, name='profile-creation'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    path('my-profile/', account_views.my_profile, name='my-profile'),
    path('my-profile/edit/', account_views.edit_profile, name='edit-profile'),
    path('view-profile/<int:user_id>/<username>/', account_views.view_profile, name='view-profile'),
]

legaltalks_src/forum/urls.py
from django.urls import path
from . import views as forum_views

app_name = 'forum'

urlpatterns = [
    path('', forum_views.search, name='search'),
    path('question/post/', forum_views.post_question, name='post-question'),
    path('question/<int:question_id>/', forum_views.question_detail, name='question-detail'),
    path('question/<int:question_id>/edit/', forum_views.edit_question, name='edit-question'),
    path('question/<int:question_id>/delete/', forum_views.question_delete, name='delete-question'),
    path('answer/edit/<int:answer_id>/', forum_views.edit_answer, name='edit-answer'),
    path('answer/delete/<int:answer_id>/', forum_views.delete_answer, name='delete-answer'),
    path('your-content/', forum_views.your_content, name='your-content'),
    path('anonymous/', forum_views.anonymous, name='anonymous'),
    path('vote/', forum_views.vote, name='vote'),
]

legaltalks_src/legaltalks/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views as account_views
from django.conf import settings
from django.conf.urls.static import static
from forum import views as forum_views

urlpatterns = [
    path('', forum_views.home , name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('forum/', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legaltalks_src/forum/models.py
from django.db import models
from django.utils import timezone
from account.models import (
    Account,
    UserProfile
)
from django.template.defaultfilters import slugify
from django.urls import reverse

class Question(models.Model):
    BUSINESS_LAW            = 'Bu'
    CIVIL_LAW               = 'Ci'
    CONSTITUTIONAL_LAW      = 'Co'
    CONSUMER_LAW            = 'Cn'
    CRIMINAL_LAW            = 'Cr'
    FAMILY_LAW              = 'Fa'
    INTELLECTUAL_PROPERTY   = 'In'
    LABOUR                  = 'La'
    PROPERTY_LAW            = 'Pr'
    TAXATION                = 'Ta'

    CATEGORY_CHOICES = [
        (BUSINESS_LAW          , 'Business Law'          ),
        (CIVIL_LAW             , 'Civil Law'             ),
        (CONSTITUTIONAL_LAW    , 'Constitutional Law'    ),
        (CONSUMER_LAW          , 'Consumer Law'          ),
        (CRIMINAL_LAW          , 'Criminal Law'          ),
        (FAMILY_LAW            , 'Family Law'            ),
        (INTELLECTUAL_PROPERTY , 'Intellectual Property' ),
        (LABOUR                , 'Labour'                ),
        (PROPERTY_LAW          , 'Property Law'          ),
        (TAXATION              , 'Taxation'              ),
    ]

    question_title   = models.CharField(max_length=150) # by form
    question_body    = models.TextField() # by form
    is_anonymous     = models.BooleanField(default=False) # by form
    
    category = models.CharField( # by form
        max_length = 2, 
        choices = CATEGORY_CHOICES
    )

    author          = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='questions')
    upvotes         = models.ManyToManyField(Account, related_name='q_upvoters', blank=True)
    downvotes       = models.ManyToManyField(Account, related_name='q_downvoters', blank=True)
    date_asked      = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-date_asked']

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        return self
    def get_absolute_url(self):
        return reverse('forum:question-detail', kwargs={'question_id': self.pk})
    def answer_count(self):
        return len(self.answer_set.all())
    def votes(self):
        return len(self.upvotes.all()) - len(self.downvotes.all())

class Answer(models.Model):
    answer_for      = models.ForeignKey(Question, on_delete=models.CASCADE) # Override Save for form
    date_answered   = models.DateTimeField(default=timezone.now)
    answer_body     = models.TextField() # by form
    upvotes         = models.ManyToManyField(Account, related_name='a_upvoters', blank=True)
    downvotes       = models.ManyToManyField(Account, related_name='a_downvoters', blank=True)
    is_anonymous    = models.BooleanField(default=False) # by form
    answerer        = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='answers') # Override Save for form
    def votes(self):
        return len(self.upvotes.all()) - len(self.downvotes.all())

legaltalks_src/forum/forms.py
from django import forms
from .models import Question, Answer
from django.conf import settings

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = (
            'is_anonymous',
            'category',
            'question_title',
            'question_body',
        )

    def save(self, usr=None, commit=True, *args, **kwargs):
        question = super().save(commit=False)
        if usr is not None:
            question.author = usr
        if commit:
            question.save()
        return question

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = (
            'is_anonymous',
            'answer_body'
        )

    def save(self, usr=None, ques=None, commit=True, *args, **kwargs):
        answer = super().save(commit=False)
        if usr is not None:
            answer.answerer = usr
        if ques is not None:
            answer.answer_for = ques
        if commit:
            answer.save()
        return answer

legaltalks_src/forum/views.py
# Balance - In CRUD views add the handling for DoesNotExist
from django.shortcuts import render, redirect
from .models import Question, Answer
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    ListView,
)
from .forms import QuestionForm, AnswerForm
from operator import itemgetter
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

def home(request):
    try:
        if request.session['category'] and request.user.is_authenticated:
            pending_question = Question(
                question_title=request.session['question_title'],
                question_body=request.session['question_body'],
                is_anonymous=request.session['as_anonymous'],
                category=request.session['category'],
                author=request.user
            )
            new_question = pending_question.save()
            request.session.pop('as_anonymous', None)
            request.session.pop('category', None)
            request.session.pop('question_title', None)
            request.session.pop('question_body', None)
            request.session.modified = True
            messages.success(request, f'Your Query has been posted {new_question.author.first_name}!')
            return redirect(new_question.get_absolute_url())
    except KeyError:
        questions = []
        for q in Question.objects.all():
            answer_count = len(q.answer_set.all())
            votes = q.votes()
            question_category = q.get_category_display()
            questions.append((q, answer_count, votes, question_category))
        context = {
            'questions': questions,
        }
        return render(request, 'forum/home.html', context)

def post_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            if request.user.is_authenticated:
                new_question = form.save(request.user)
                messages.success(request, f'Your Query has been posted {new_question.author.first_name}!')
                return redirect(new_question.get_absolute_url())
            request.session['as_anonymous'] = form.cleaned_data.get('is_anonymous')
            request.session['category'] = form.cleaned_data.get('category')
            request.session['question_title'] = form.cleaned_data.get('question_title')
            request.session['question_body'] = form.cleaned_data.get('question_body')
            return redirect('account:login')
    return redirect('home')


@login_required
def edit_question(request, question_id):
    if request.method == 'POST':
        question = Question.objects.get(pk=question_id)
        edit_question_form = QuestionForm(request.POST, instance=question)
        if edit_question_form.is_valid():
            edit_question_form.save()
            messages.success(request, 'Your Question was updated Successfully!')
            return redirect(question.get_absolute_url())
        messages.error(request, 'Failed to save edits to your Question')
        return redirect(question.get_absolute_url())
    return redirect('home')

def question_detail(request, question_id):
    question = Question.objects.get(pk=question_id)
    if request.method == 'POST':
        answer_form = AnswerForm(request.POST)
        if answer_form.is_valid():
            answer_form.save(usr=request.user, ques=question)
            messages.success(request, 'Your Answer was successfully added to this Question!')
            return redirect(question.get_absolute_url())
        messages.error(request, 'An error occured while adding your answer to this question.')
        return redirect(question.get_absolute_url())
    question_edit_form = QuestionForm(instance=question)
    votes = question.votes()
    answer_count = len(question.answer_set.all())
    answer_form = AnswerForm()
    context = {
        'question': question,
        'question_edit_form': question_edit_form,
        'votes': votes,
        'answer_count': answer_count,
        'answer_form': answer_form,
    }
    return render(request, 'forum/question.html', context)

def question_delete(request, question_id):
    if request.method == 'POST':
        Question.objects.get(pk=question_id).delete()
        messages.success(request, 'Your Question Was Deleted Successfully!')
        return redirect('home')
    return redirect('home')

""" class HomeQuestionListView(ListView):
    model = Question
    template_name = 'forum/home.html'
    context_object_name = 'question'
    ordering = ['-date_asked'] """

def edit_answer(request, answer_id):
    if request.method == 'POST':
        answer = Answer.objects.get(pk=answer_id)
        anonymity = request.POST.get('answer_anonymity', False)
        if anonymity == 'on':
            anonymity = True
        else:
            anonymity = False
        answer.is_anonymous = anonymity
        answer.answer_body = request.POST['edit_question_body']
        answer.save()
        messages.success(request, 'Your Answer Has Been Edited Successfully')
        question = answer.answer_for
        return redirect(question.get_absolute_url())
    return redirect('home')

def delete_answer(request, answer_id):
    if request.method == 'POST':
        answer = Answer.objects.get(pk=answer_id)
        question = answer.answer_for
        answer.delete()
        messages.success(request, 'Your Answer Has Been Deleted Successfully')
        return redirect(question.get_absolute_url())
    else:
        redirect('home')

@login_required
def your_content(request):
    user = request.user
    your_content = []
    if user.is_advocate:
        for q in user.questions.all():
            question = q, q.date_asked, "q"
            your_content.append(question)
        for a in user.answers.all():
            answer = a, a.date_answered, "a"
            your_content.append(answer)
        your_content.sort(key=itemgetter(1), reverse=True)
    else:
        for q in user.questions.all():
            question = q, q.date_asked, "q"
            your_content.append(question)
        your_content.sort(key=itemgetter(1), reverse=True)
    return render(request, 'forum/yourContent.html', {'your_content': your_content})


def search(request):
    keywords = request.GET.get("search", False)
    if keywords:
        keywords = keywords.split()
        results = []
        # Tests whether the search returned at least one result
        found = False
        for question in Question.objects.all():
            question_text = question.question_title + question.question_body
            question_text =  question_text.casefold()
            # Tests whether at least one keyword matches
            # And used to determine whether to include the current question
            matched = False
            degree = 0
            for keyword in keywords:
                if keyword.casefold() in question_text:
                    if not matched:
                        matched = True
                        found = True
                    degree += 1
            if matched:
                results.append((question, degree))
        if not found:
            results = False
        else:
            results.sort(key=itemgetter(1), reverse=True)
        context = {
            'results': results,
            'keywords': keywords,
        }
        return render(request, 'forum/search.html', context)
    else:
        return render(request, 'forum/search.html', {})

def anonymous(request):
    return render(request, 'forum/anonymous.html', {})

@csrf_exempt
def vote(request):
    if request.method == 'POST' and request.user.is_authenticated:
        act = {}
        act[0] = request.POST.get("0")
        act[1] = request.POST.get("1")
        forum_obj = request.POST.get("forum_obj")
        # Check whether it is the question or answer which is being interacted
        if forum_obj == "q":
            q_id = int(request.POST.get("question"))
            obj = Question.objects.get(id=q_id)
        else:
            obj = Answer.objects.get(id=int(forum_obj))
        print(act)
        print(obj)
        # Check which button was pressed
        if act[0] == "up":
            if act[1] == "add_upvote":
                if request.user in obj.downvotes.all():
                    obj.downvotes.remove(request.user)
                obj.upvotes.add(request.user)
            else:
                obj.upvotes.remove(request.user)
            obj.save()
        else:
            if act[1] == "add_downvote":
                if request.user in obj.upvotes.all():
                    obj.upvotes.remove(request.user)
                obj.downvotes.add(request.user)
            else:
                obj.downvotes.remove(request.user)
            obj.save()
        obj.refresh_from_db()
        return JsonResponse({"votes": obj.votes()})
    return JsonResponse({"login": "/account/login/"})
    # return JsonResponse({"success": "Succeeded Successfully!"})

legaltalks_src/forum/templates/forum/anonymous.html
{% extends 'forum/base.html' %}
{% load static %}
{% block css_file %}
    href="{% static 'forum/anonymous.css' %}"
{% endblock css_file %}

{% block title %}LegalTalks | Anonymous User{% for keyword in keywords %}{{ keyword }} {% endfor %}{% endblock title %}

{% block active_nav_link %}
    {# ---- Home Nav ----- #}
    <li class="nav-item active navs">
        {# -Done Balance - href in below tag #}
        <a class="nav-link" href="{% url 'home' %}" data-toggle="tooltip" data-placement="bottom" title="Home"><i
                class="fa fa-home"></i></a>
    </li>

    {# Your Content Nav #}
    <li class="nav-item active navs">
        {# Done - Balance - href in below tag #}
        <a class="nav-link" href="{% url 'forum:your-content' %}" data-toggle="tooltip" data-placement="bottom" title="Your Content"><i
                class="fa fa-edit"></i></a>
    </li>

    {# Profile Nav #}
    <li class="nav-item active navs">
        {# Done - Balance - href in below tag #}
        <a class="nav-link nav-profile" href="{% url 'account:my-profile' %}" data-toggle="tooltip" data-placement="bottom" title="Profile">
            {% if user.is_authenticated %}
                {% if user.is_advocate %}
                    <img class="img-fluid rounded-circle" src="{{ user.userprofile.profile_image.url }}">
                {% else %}
                    <img class="img-fluid rounded-circle" src="{{ user.commonuserprofile.profile_image.url }}">
                {% endif %}
            {% else %}
                <i class="fa fa-user-circle"></i>
            {% endif %}
        </a>
    </li>
{% endblock active_nav_link %}

{% block main_content %}
    <h4 class="about-heading text-center">About</h4>
    <hr>
    <div class="row mt-5">
        <div class="col-lg-6 col-md-12 col-sm-12">
            <div class="anonymous-image">
                <img class="img-fluid" src="/media/anonymous.jpg">
            </div>
        </div>

        <div class="col-lg-6 col-md-12 col-sm-12">
            <div class="anonymous-heading">
                <h1 class="text-center">This <br> User <br>Chooses <br> To Be <br> Anonymous</h1>
            </div>
        </div>
    </div>
{% endblock main_content %}

legaltalks_src/forum/templates/forum/base.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- CSS -->
        {% comment %} href="{% static 'forum/index.css' %}" {% endcomment %}
        <link rel="stylesheet" {% block css_file %}{% endblock css_file %}  >
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">   
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

        <title>
        {% block title %}

        {% endblock title %}
        </title>
        <link rel="icon" href="{% static 'forum/legaltalks_logo.png' %}">
    </head>
    <body>
        {# ------- Navbar Start --------- #}
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container">
            
                {# ---- Logo ---- #}
                {# -Done Balance - href in below tag #}
                <a class="navbar-brand" href="{% url 'home' %}"><strong>LEGAL<img src="{% static 'forum/legaltalks_logo.png' %}">TALKS</strong></a>

                {# ---- Navbar Toggler ----- #}
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">

                        {% block active_nav_link %}{% endblock active_nav_link %}

                        {# Add Question Button #}
                        <li class="nav-item active navs">
                            <button id="add_question" type="button" class="btn btn-outline-primary" data-toggle="modal"
                                data-target="#add-question-modal" data-toggle="tooltip" data-placement="top"
                                title="Add Question"><i class="fa fa-plus"></i></button>
                        </li>

                        {# Search Bar #}
                        {# Balance - specify the action attribute below #}
                        <form class="my-2 my-lg-0" action="{% url 'forum:search' %}" method="GET">
                            <div class="input-group">
                                <input id="search" class="form-control" name="search" type="search" placeholder="Search" {% if keywords %}value="{% for keyword in keywords %}{{ keyword }} {% endfor %}"{% endif %}>
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>

                        {% if user.is_authenticated %}
                            <li id="login-signup-btns" class="nav-item active navs">
                                <a href="{% url 'account:logout' %}" class="btn btn-outline-warning">Logout</a>
                            </li>
                        {% else %}
                            {# Login & SignUp #}
                            <li id="login-signup-btns" class="nav-item active navs">
                                <a href="{% url 'account:login' %}" class="btn btn-outline-warning">Login</a>
                                <a href="{% url 'account:user-signup' %}" class="btn btn-outline-warning">Sign Up</a>
                            </li>
                        {% endif %}

                        {# About Nav #}
                        <li class="nav-item active navs">
                            {# Balance - href in below tag #}
                            <a class="nav-link" href="#" data-toggle="tooltip" data-placement="bottom" title="About"><i
                                    class="fa fa-info-circle" aria-hidden="true"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {# Add Question Modal Start #}
        <div class="modal fade" id="add-question-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">

                        {# Modal Title Add Question #}
                        <h5 class="modal-title" id="exampleModalLabel">Add Question</h5>

                        {# Close Button #}
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="{% url 'forum:post-question' %}" method="POST">
                        {% csrf_token %}
                        <div class="modal-body">
                            {# Anonymous ON/OFF #}
                            <div class="form-check">
                                {% render_field question_form.is_anonymous class="form-check-input" id="is-anonymous" %}
                                <label class="form-check-label" for="is-anonymous">
                                    Post As Anonymous?
                                </label>
                            </div>
                            <hr>

                            {# Categories Start #}
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="inputGroupSelect01">Categories</label>
                                </div>
                                {% render_field question_form.category class="custom-select" id="inputGroupSelect01" %}
                            </div>
                            {# Categories End #}

                            {# Add Question TextArea #}
                            {% render_field question_form.question_title class="form-control text-body" id="add-question-title" placeholder="Question Title" style="color: #666b71 !important;"%}

                            {% render_field question_form.question_body class="form-control" id="add-question-detail" placeholder="Start your Question with What, How, Why, etc." %}

                        </div>

                        {# Modal Footer Start #}
                        <div class="modal-footer">

                            {# Add Question Button #}
                            <button type="submit" class="btn btn-danger">Add Question</button>

                            {# Close Button #}
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                    {# Modal Footer End #}

                </div>
            </div>
        </div>

        {# Add Question Modal End #}

        {# ------------------ NAVBAR ------------------ #}

        {# Answer Modal Start #}

        {% comment %} <div class="modal fade" id="answer-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">

                    {# Modal Title Add Question #}
                    <h5 class="modal-title" id="exampleModalLabel">Add Answer</h5>

                        {# Close Button #}
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>

                    </div>


                    <div class="modal-body">

                        {# Add Answer Textarea #}
                        <textarea class="form-control" id="add-question-detail"
                            placeholder="Write Your Answer Here."></textarea>
                    </div>

                    {# Modal Foooter Start #}
                    <div class="modal-footer">

                        {# Close Button #}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                        {# Add Question Button #}
                        <button type="button" class="btn btn-danger">Submit</button>
                    </div>
                    {# Modal Foooter End #}

                </div>
            </div>
        </div> {% endcomment %}

        {# Answer Modal End #}


        {# Report Modal Start #}

        <div class="modal fade" id="report-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">

                        {# Modal Title Add Question #}
                        <h5 class="modal-title" id="exampleModalLabel">Report Question</h5>

                        {# Close Button #}
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>

                    </div>

                    <div class="modal-body">
                        {# Add Answer Textarea #}
                        <p>Are you sure you want to report this question?</p>

                    </div>
                    {# Modal Foooter Start #}
                    <div class="modal-footer">
                        {# Close Button #}
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        {# Add Question Button #}
                        <button type="button" class="btn btn-danger">Report</button>
                    </div>
                    {# Modal Foooter End #}

                </div>
            </div>
        </div>

        {# Report Modal End #}

        {# ------------------ Main Content Start ------------------ #}
        {% block main_content %}{% endblock main_content %}
        {# ------------------ Main Content End ------------------ #}

        <!-- JavaScript -->
        <script>

        </script>
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
        {% block custom_script %}{% endblock custom_script %}
    </body>
</html>